development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: adeliegames_development
  pool: 10
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: adeliegames_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1
